# docker-compose.yml
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: rico-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      # Authentication - change this password!
      - NEO4J_AUTH=neo4j/ricograph123
      # Memory Configuration
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      # Performance
      - NEO4J_db_transaction_timeout=120s
      - NEO4J_db_lock_acquisition_timeout=120s
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build: ./api
    container_name: rico-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - API_KEY=${API_KEY}
      - SEARCH_CARRIERS_API_TOKEN=${SEARCH_CARRIERS_API_TOKEN}
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./api:/app  # For development hot-reload

volumes:
  neo4j_data:
  neo4j_logs: