version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: rico-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf
      - ./backup:/backup
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/testpassword123
      # Memory Configuration (adjust based on your VPS)
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      # Security
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # Performance
      - NEO4J_db_transaction_timeout=120s
      - NEO4J_db_lock_acquisition_timeout=120s
      # Networking
      - NEO4J_server_default__listen__address=0.0.0.0
      # Disable strict validation to avoid config issues
      - NEO4J_server_config_strict__validation_enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build: ./api
    container_name: rico-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword123
      - API_KEY=test-api-key-123
    depends_on:
      - neo4j
    volumes:
      - ./api:/app
      - ./logs/api:/app/logs

networks:
  default:
    name: rico-network